[project]
# Future trIples extracTION
name = "fiction"
version = "0.1.0"
description = ""
requires-python = ">=3.9,<3.11"
dependencies = [
    "accelerate>=1.6.0",
    "bitsandbytes<0.42",
    "joblib>=1.5.0",
    "more-itertools>=10.7.0",
    "numpy>=2.0.2",
    "pandas>=2.2.3",
    "scienceplots>=2.1.1",
    "scikit-learn>=1.6.1",
    "torch>=2.7.0",
    "tqdm>=4.67.1",
    "transformers>=4.51.3",
    "requests>=2.32.3",
    "openai>=2.24.0",
]

[dependency-groups]
dev = [
    "pytest",
    "hypothesis"
]

[project.optional-dependencies]
cpu = [
  "torch>=2.7.0",
]
cuda128 = [
  "torch>=2.7.0",
]

[tool.uv]
conflicts = [
  [
    { extra = "cpu" },
    { extra = "cuda128" },
  ],
]

[tool.uv.sources]
torch = [
  { index = "pytorch-cpu", extra = "cpu" },
  { index = "pytorch-cuda128", extra = "cuda128" },
]

[[tool.uv.index]]
name = "pytorch-cpu"
url = "https://download.pytorch.org/whl/cpu"
explicit = true

[[tool.uv.index]]
name = "pytorch-cuda128"
url = "https://download.pytorch.org/whl/cu128"
explicit = true
